import React from "react";
import { Link2, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";

export default function AccountSettings() {
  const links = trpc.account.identityLinks.useQuery();
  return <main className="cyber-grid min-h-screen pb-14 pt-6 sm:pt-10"><div className="container max-w-3xl space-y-5"><header className="cyber-panel p-5 sm:p-7"><p className="autonomy-kicker">ACCOUNT // IDENTITY LINKS</p><h1 className="mt-2 text-3xl font-bold text-white">Konten sicher verknüpfen.</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Verbinde Google nachträglich mit deinem bestehenden CyberSarah-Profil. Deine aktuelle Sitzung bleibt erhalten; eine fremde oder bereits verknüpfte Google-Identität wird abgewiesen.</p></header><section className="cyber-panel p-5 sm:p-6" aria-labelledby="provider-links-title"><div className="flex items-center gap-3"><Link2 className="h-5 w-5 text-cyan-200" /><h2 id="provider-links-title" className="text-lg font-semibold text-white">Verknüpfte Anmeldungen</h2></div>{links.isLoading ? <p className="mt-4 text-sm text-muted-foreground">Status wird geladen …</p> : <div className="mt-4 space-y-3"><div className="flex flex-col gap-3 rounded-xl border border-cyan-300/15 bg-cyan-300/[0.04] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-white">Manus OAuth</p><p className="mt-1 text-xs text-muted-foreground">Aktive primäre Sitzung</p></div><span className="rounded-full border border-emerald-200/20 bg-emerald-200/10 px-3 py-1 text-xs text-emerald-100">Aktiv</span></div>{links.data?.some(link => link.provider === "google") ? <div className="flex flex-col gap-3 rounded-xl border border-emerald-300/15 bg-emerald-300/[0.04] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-white">Google</p><p className="mt-1 text-xs text-muted-foreground">Verknüpft · E-Mail wird nicht öffentlich angezeigt</p></div><span className="rounded-full border border-emerald-200/20 bg-emerald-200/10 px-3 py-1 text-xs text-emerald-100">Verknüpft</span></div> : <div className="rounded-xl border border-amber-300/15 bg-amber-300/[0.04] p-4"><p className="font-medium text-white">Google</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Noch nicht verknüpft. Der OAuth-Flow startet in einem neuen sicheren Navigationsschritt.</p><Button className="mt-4 min-h-11 w-full sm:w-auto" onClick={() => window.location.assign("/api/oauth/google/link")}><Link2 className="mr-2 h-4 w-4" />Google-Konto verknüpfen</Button></div>}</div>}</section><section className="cyber-panel border-amber-300/15 p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-amber-200" /><p className="text-xs leading-5 text-amber-50/80">Sicherheitsregel: E-Mail-Übereinstimmung allein verknüpft kein Konto. Nur die erfolgreiche Google-Authentifizierung mit gültigem State, PKCE und verifizierter Identität kann eine Verknüpfung anlegen.</p></div></section><Link href="/" className="inline-block text-sm text-cyan-200 underline">Zurück zum Dashboard</Link></div></main>;
}
