import React from "react";
import { Link } from "wouter";

export default function PlayStorePolicy({ kind }: { kind: "privacy" | "terms" | "deletion" }) {
  const content = {
    privacy: { title: "Datenschutzerklärung", intro: "CyberSarah Revenue OS verarbeitet Kontodaten, Workspace-Daten und betriebliche Revenue-Signale nur für Authentifizierung, Analyse und vom Nutzer freigegebene Abläufe.", sections: ["OAuth-Sitzungen werden serverseitig verwaltet; Secrets und Provider-Credentials werden nicht in den Frontend-Build eingebettet.", "Funnel-, Experiment- und Revenue-Signale werden pseudonymisiert beziehungsweise arbeitsbereichsbezogen für Attribution und interne Optimierung verarbeitet.", "Keine Zahlung, Nachricht, Veröffentlichung oder CRM-Außenwirkung wird ohne explizite Freigabe ausgelöst."] },
    terms: { title: "Nutzungsbedingungen", intro: "CyberSarah Revenue OS ist ein Revenue-Operations-Arbeitsbereich für überprüfbare interne Analysen und freigabepflichtige Entwürfe.", sections: ["Interne Automatisierung erstellt Empfehlungen und Drafts. Nutzer bleiben für die Freigabe externer Wirkungen verantwortlich.", "Providerstatus, Sandbox-Daten und Metriken dürfen nicht als Zusage einer erfolgreichen Zahlung, Veröffentlichung oder Umsatzhöhe verstanden werden.", "Abo- und Zahlungsbedingungen müssen vor einem Google-Play-Release mit dem tatsächlich konfigurierten Billing-Provider ergänzt werden."] },
    deletion: { title: "Account- und Datenlöschung", intro: "Wenn Sie Ihren CyberSarah-Account und die zugehörigen Daten löschen möchten, starten Sie den authentifizierten Löschprozess im Arbeitsbereich oder wenden Sie sich an den Betreiber.", sections: ["Die Löschanforderung muss dem authentifizierten Account eindeutig zugeordnet werden.", "Daten, die für gesetzliche Nachweise oder Sicherheit erforderlich sind, können nur im zulässigen Umfang und mit dokumentierter Begründung aufbewahrt werden.", "Dieser öffentliche Informationspfad ist eingerichtet; die produktive Löschverarbeitung und die Play-Console-Datenlöschungsangaben müssen vor Veröffentlichung separat aktiviert und verifiziert werden."] },
  }[kind];
  return <main className="cyber-grid min-h-screen px-4 py-10 text-foreground"><article className="cyber-panel mx-auto max-w-3xl p-6 sm:p-10"><Link href="/" className="mono text-xs text-cyan-200">← CyberSarah Revenue OS</Link><p className="mono mt-8 text-[10px] tracking-[0.18em] text-cyan-200">PUBLIC POLICY // {kind.toUpperCase()}</p><h1 className="mt-3 text-3xl font-bold text-white">{content.title}</h1><p className="mt-4 text-sm leading-7 text-muted-foreground">{content.intro}</p><div className="mt-8 space-y-4">{content.sections.map(section => <p key={section} className="rounded-xl border border-border/70 bg-background/30 p-4 text-sm leading-7 text-muted-foreground">{section}</p>)}</div></article></main>;
}
