import React from "react";
import { ArrowLeft, ShieldAlert, TrendingUp } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

export default function TradingPanel() {
  const status = trpc.trading.status.useQuery();
  if (status.isLoading) return <section className="cyber-panel p-6 text-sm text-muted-foreground">Trading-Readiness wird geladen …</section>;
  const snapshot = status.data;
  return <main className="space-y-5"><header className="cyber-panel p-5 sm:p-6"><Link href="/hara" className="inline-flex items-center gap-2 text-xs text-cyan-200"><ArrowLeft className="h-4 w-4" /> Zur HARA-Zentrale</Link><div className="mt-5 flex items-start justify-between gap-4"><div><p className="mono text-[10px] tracking-[0.18em] text-cyan-200">TRADING INTELLIGENCE // DRY-RUN</p><h1 className="mt-2 text-3xl font-bold text-white">Freqtrade-Status</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Micro-Trading bleibt ein getrenntes Analysemodul. Orders und Live-Ausführung sind im Revenue OS nicht automatisch möglich.</p></div><TrendingUp className="hidden h-6 w-6 text-cyan-200 sm:block" /></div></header><section className="grid gap-3 sm:grid-cols-3"><div className="cyber-panel p-4"><p className="mono text-[10px] text-cyan-200">MODUS</p><p className="mt-2 text-xl font-bold text-white">{snapshot?.mode ?? "unconfigured"}</p></div><div className="cyber-panel p-4"><p className="mono text-[10px] text-cyan-200">ROI</p><p className="mt-2 text-xl font-bold text-white">{snapshot?.roi === null || snapshot?.roi === undefined ? "Nicht verfügbar" : `${snapshot.roi.toFixed(2)}%`}</p></div><div className="cyber-panel p-4"><p className="mono text-[10px] text-cyan-200">OFFENE TRADES</p><p className="mt-2 text-xl font-bold text-white">{snapshot?.openTrades ?? "Nicht verfügbar"}</p></div></section><article className="cyber-panel border-amber-300/20 p-5"><div className="flex items-start gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-200" /><div><h2 className="font-semibold text-white">Risk & Governance</h2><p className="mt-2 text-sm leading-6 text-slate-300">{snapshot?.message ?? "Keine Freqtrade-Konfiguration erkannt."}</p><p className="mt-3 text-xs text-amber-100">Live-Trading: blockiert · Approval erforderlich: ja · Externe Ausführung: nein</p></div></div></article><section className="cyber-panel p-5"><h2 className="font-semibold text-white">Strategy-Readiness</h2><p className="mt-2 text-sm text-slate-300">Strategy: <strong>{snapshot?.strategy ?? "nicht verbunden"}</strong></p><p className="mt-2 text-xs leading-5 text-muted-foreground">Für einen echten Dry-Run müssen Freqtrade-URL und Token als verwaltete Secrets gesetzt werden. Es werden keine Test- oder Dummy-Credentials in das Projekt geschrieben.</p></section></main>;
}
