import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import agentsRouter from "./agents";
import campaignsRouter from "./campaigns";
import contentRouter from "./content";
import financeRouter from "./finance";
import agentLogsRouter from "./agentLogs";
import orchestratorRouter from "./orchestrator";
import revenueRouter from "./revenue";
import systemStatusRouter from "./systemStatus";
import expansionRouter from "./expansion";
import sofortStartRouter from "./sofortStart";
import tradingRouter from "./trading";
import masterRouter from "./master";
import einstellungenRouter from "./einstellungen";
import influencerRouter from "./influencer";
import storageRouter from "./storage";
import financeTeamRouter from "./financeTeam";
import haraRouter from "./hara";
import seoContentRouter from "./seoContent";
import newsletterRouter from "./newsletter";
import influencerCoreRouter from "./influencerCore";
import whatsappRouter from "./whatsapp";
import masterAgentV2Router from "./masterAgentV2";
import digistoreRouter from "./digistore";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(agentsRouter);
router.use(campaignsRouter);
router.use(contentRouter);
router.use(financeRouter);
router.use(agentLogsRouter);
router.use(orchestratorRouter);
router.use(revenueRouter);
router.use(systemStatusRouter);
router.use(expansionRouter);
router.use(sofortStartRouter);
router.use(tradingRouter);
router.use(masterRouter);
router.use(einstellungenRouter);
router.use(influencerRouter);
router.use(storageRouter);
router.use(financeTeamRouter);
router.use(haraRouter);
router.use(seoContentRouter);
router.use(newsletterRouter);
router.use(influencerCoreRouter);
router.use(whatsappRouter);
router.use(masterAgentV2Router);
router.use(digistoreRouter);

export default router;
